// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwwB4zHD8iRilA3fxyteFRMAEKWnI8y5I',
    appId: '1:855972287164:web:1866d99964d564e55f76b9',
    messagingSenderId: '855972287164',
    projectId: 'katomaran-todoapp',
    authDomain: 'katomaran-todoapp.firebaseapp.com',
    storageBucket: 'katomaran-todoapp.firebasestorage.app',
    measurementId: 'G-KZS3T0MNBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxmBcHUC0EpxKRg_rzGgFLFdbDLjb4oLc',
    appId: '1:855972287164:android:ef51d184b3d6cfee5f76b9',
    messagingSenderId: '855972287164',
    projectId: 'katomaran-todoapp',
    storageBucket: 'katomaran-todoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDADVyyikQpS_IXNVsECnrD4DLq4pgCrbk',
    appId: '1:855972287164:ios:7ed14e7c1400d88b5f76b9',
    messagingSenderId: '855972287164',
    projectId: 'katomaran-todoapp',
    storageBucket: 'katomaran-todoapp.firebasestorage.app',
    iosBundleId: 'com.example.katomaranTodoapp',
  );

}
